export const normalize=s=>s.normalize('NFKD').replace(/\p{M}/gu,'').toLowerCase().replace(/ß/g,'ss').replace(/[^\p{L}\p{N}]/gu,'');
export const escape=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
export function sentences(text){
 const safe=text.replace(/\b(?:Mr|Mrs|Ms|Dr|Prof|St|Bros|Jr|Sr)\./g,s=>s.replace('.','\uE000')).replace(/\b(?:[A-Z]\.){2,}/g,s=>s.replaceAll('.','\uE000'));
 return [...new Intl.Segmenter('en',{granularity:'sentence'}).segment(safe)].flatMap(x=>x.segment.trim().split(/;\s+|,\s+(?:while|but)\s+(?=(?:Charlie|Alan|Jake|Walden|Judith|Evelyn|Berta|Rose|Chelsea|Lyndsey|Herb|Kandi|Mia|Melissa)\b)/)).map(x=>{let s=x.trim().replaceAll('\uE000','.');s=s.charAt(0).toUpperCase()+s.slice(1);return /[.!?]["”’')]*$/.test(s)?s:s+'.';});
}
export const main=['Charlie Harper','Alan Harper','Jake Harper','Walden Schmidt','Berta','Evelyn Harper','Judith Harper'];
const men=['Charlie Harper|Charlie','Alan Harper|Alan','Jake Harper|Jake','Walden Schmidt|Walden','Herb Melnick|Herb','Eldridge McElroy|Eldridge|Eldrige','Teddy Leopold|Teddy','Gordon','Billy Stanhope|Billy','Barry Foster|Barry','Larry Martin|Larry','Marty Pepper|Marty','Louis','Jeff Strongman','Sam Wilson','Archie Baldwin|Archie','Russell','Brad','Manny','Chris','Danny','Eric','Harry','Greg','Fernando','Brandon','Nick','Andy','Norman','Jerome','Nathan Krunk','Tom','Ed','Victor','Nigel','Sid Olsen','Steven','Jerry','Chuck','Derek','Bobby','Nathan','Dwight','Leo','Bill','Philip','Milton','Sperlock','Jim','Gabe','Henry','Santa Claus|Santa'];
const women=['Berta','Evelyn Harper|Evelyn','Judith Harper|Judith','Rose','Kandi','Chelsea Melini|Chelsea','Lyndsey McElroy|Lyndsey|Lindsey','Mia','Bridget Schmidt|Bridget','Zoey','Jenny Harper|Jenny','Melissa','Kate','Robin Schmidt|Robin','Dr. Linda Freeman|Dr. Freeman|Freeman','Ava','Courtney Leopold|Courtney','Gretchen','Miss McMartin|Ms. McMartin|Ms McMartin|McMartin','Miss Pasternak|Delores Pasternak|Pasternak','Lisa','Prudence','Frankie','Laura','Norma','Lydia','Myra','Gloria','Sherri','Isabella','Naomi','Celeste','Tammy','Gail','Brooke','Nicole','Paula','Missi','Jill','Laurel','Kiki','Megan','Francine','Daisy','Wendy','Sandy','Kimber','Angie','Wanda','Betsy','Esmeralda','Chloe','Michelle','Danielle','Gabrielle','Chrissy','Mercedes','Martha','Nadine','Gwen','Rachel','Ashley','Whitney','Meghan','Laurie','Kathy','Jennifer','Vivian','Stephanie','Linda Harris|Judge Linda Harris','Barbara','Sally','Milly','Sylvia Fishman','Trudy','Nancy','Sara','Sarah'];
export const people=[...men.map(s=>[s,'male']),...women.map(s=>[s,'female'])].map(([text,group])=>{const [name,...aliases]=text.split('|');return {name,aliases,group,kind:'character',forms:[name,...aliases]};});
// Named objects, locations, activities and exact details, grouped for plausible distractors.
const groups={
 place:['Las Vegas','Malibu','Paris','London','New York','New York City','San Francisco','Los Angeles','Japan','China','Mexico','Hawaii','Beverly Hills','Seattle','Denver','Fiji','Costa Rica','Grand Canyon','Montana','Africa','Germany','Boston','Cleveland','Ibiza','Sherman Oaks','Canada'],
 game:['poker','Scrabble','chess','golf','miniature golf','bowling','basketball','baseball','soccer','football','tennis','volleyball','video games','backgammon','swimming','surfing','ballet','opera','karaoke','yoga'],
 object:['piano','guitar','saxophone','trumpet','drums','violin','helicopter','Ferrari','Porsche','Mercedes','Rolex','Lamborghini','Fisker Karma','motorcycle','bicycle','trampoline','wedding ring','diamond ring','engagement ring','cigars','whiskey','cigarettes','pipe','asthma inhaler','puppet','puppets','ventriloquist dummy','wedding dress','couch','sofa','refrigerator','toothbrush','wedding cake','handcuffs','laptop','credit card','passport','diary','ashtray','urn','knife','samurai sword','box of chocolates','flowers','roses','teddy bear','underwear','condom','condoms','birth control pills','Christmas tree'],
 animal:['seagulls','ferrets','parrot','monkey','chimpanzee','dog','cat','goat','snake','hamster','fish','dolphin','penguin','rat','horse','donkey','pony','tiger','lion','cow'],
 food:['brownies','pizza','sushi','chocolate','turkey','pancakes','waffles','cheesecake','muffins','cookies','ice cream','spaghetti','chili','hamburgers','cheeseburger','cheesesteak','lasagna','meatloaf','Chinese food','lobster','shrimp','coffee','milk','beer','vodka','wine','lemon','cinnamon','Maple Loops'],
 detail:['Christmas','Thanksgiving','Halloween','Valentine’s Day','Valentine\'s Day','New Year’s Eve','Microsoft','Google','Facebook','eBay','Army','Navy','Air Force','Marines','vasectomy','colonoscopy','circumcision','plastic surgery','breast reduction','heart attack','food poisoning','pregnancy','sleepwalking','insomnia','pneumonia','flu','heart surgery','kidney stones','diabetes','chlamydia','gonorrhea','alimony','child support','custody','prenuptial agreement','restraining order','probation','community service','identity theft','bankruptcy','divorce','adoption','wedding','funeral','birthday','bar mitzvah','bachelor party','baby shower','Alan Cousteau','Charlie Waffles','Pavlov’s','Pavlov\'s','WALD-E','Electronic Suitcase','Zippy','Magilla']
};
export const terms=Object.entries(groups).flatMap(([group,items])=>items.map(name=>({name,forms:[name],group,kind:'text',aliases:[]})));
people.push(...['Artie','Lieutenant Wagner','Christian Slater','Chuck Lorre'].map(name=>({name,aliases:[],forms:[name],group:'male',kind:'character'})),...['Cynthia','Shelly'].map(name=>({name,aliases:[],forms:[name],group:'female',kind:'character'})));
const extra={activity:['dinner','interview','ventriloquism','ballroom dancing','algebra','concert','couples therapy','stage fright','drunkenness','hair loss','back pain','cold','hernia examination','royalties','death certificate','telephone number','hair-growth pills','approval','commitment','children’s songs'],location:['bookstore','restaurant','cinema','bar','coffee shop','shower','bathroom','courtroom','street','laundry room','terrace','condominium','apartment'],item:['newspaper','pretzels','bowl','dresser','house key','pillows','towels','shower curtain','ceramic roosters','litter box','Sea Breeze','pineapple','wedding video','spray','Sir Lancelot','four years','two and a half million dollars','Winning']};
terms.push(...Object.entries(extra).flatMap(([group,items])=>items.map(name=>({name,forms:[name],group,kind:'text',aliases:[]}))));
const more={activity:['dance troupe','dance performance','sperm donation','sperm','fatherhood','proposal','marriage','affair','engagement','date','therapy','massage','audition','acting','singing','dating','sex','shopping','gambling','reunion','rehab','retirement','circus','school play','school','college','high school','private school','boarding school','summer camp','concert tickets','lap dance','strip club','credit-card debt','debt','business','chiropractic practice','chiropractor','doctor','dentist','lawyer','judge','pharmacist','psychiatrist','therapist','housekeeper','receptionist','real estate','commercial','jingle','jingles','commercials','children’s music','children\'s music','children\'s songs','ballet dancer','dancer','pilot','teacher','model','actress','prostitute'],location:['hotel','motel','hospital','clinic','office','prison','jail','airport','supermarket','mall','beach','school','church','police station','bathroom window','balcony','bedroom','garage','kitchen','living room','guest room','coffee table'],item:['motor home','RV','dress','ring','watch','shoes','clothes','clothing','sweater','pants','tie','suit','wig','toupee','candy','sandwich','sandwiches','cereal','soup','toast','car','taxi','bus','train','boat','yacht','check','cash','money','letter','text message','email','e-mail','video','DVD','television','TV','cell phone','phone','apology','secret','woman','women','daughter','son','mother','brother','sister','father','grandmother','grandfather','niece','nephew','girlfriend','boyfriend','ex-husband','ex-wife','roommate','neighbor','neighbour','daughter-in-law','son-in-law','mother-in-law','father-in-law']};
terms.push(...Object.entries(more).flatMap(([group,items])=>items.filter(name=>!terms.some(t=>t.name===name)).map(name=>({name,forms:[name],group,kind:'text',aliases:[]}))));
terms.push(...['Oshikuru: Demon Samurai','The Taming of the Shrew','salmon','library','advertising award','award ceremony','marriage proposal','sperm'].filter(name=>!terms.some(t=>t.name===name)).map(name=>({name,forms:[name],group:'detail',kind:'text',aliases:[]})));
export const entities=[...people,...terms].sort((a,b)=>Math.max(...b.forms.map(s=>s.length))-Math.max(...a.forms.map(s=>s.length)));
export function candidates(text,source){
 const out=[];
 for(const [index,raw]of sentences(text.split(/(?:Title quotation from|Notes?|Absent|First appearance|Last appearance)\s*:/i)[0]).entries()){
  const sentence=raw.replace(/\s+([,.;!?])/g,'$1').replace(/\s+'s/g,"'s").replaceAll('Lindsey','Lyndsey').replaceAll('Eldrige','Eldridge');
  if(sentence.length<42||sentence.length>450||!/[.!?]["”’')]*$/.test(sentence)||/^(?:He|She|They|It|This|These|Those|His|Her|Their|The two|The latter|The former)\b/.test(sentence)||/Emmy|Primetime|actor|actress|award nomination|Charlie Sheen|Jon Cryer|Conchata Ferrell|Holland Taylor|Angus T\.|Guest starring/i.test(sentence))continue;
  const covered=[];
  for(const entity of entities){
   const forms=[...entity.forms].sort((a,b)=>b.length-a.length);
   const regex=new RegExp(`(?<![\\p{L}])(?:${forms.map(escape).join('|')})(?![\\p{L}])`,entity.kind==='character'?'gu':'giu');
   const matches=[...sentence.matchAll(regex)].filter(m=>!covered.some(([start,end])=>m.index>=start&&m.index<end));
   if(!matches.length)continue;
   if(entity.kind==='text'&&matches.some(m=>/(?:\b(?:to|cannot|can|will|would|could|should|might|must|did|does|do|they|we)|n't)\s+$/i.test(sentence.slice(0,m.index))))continue;
   for(const m of matches)covered.push([m.index,m.index+m[0].length]);
   let masked=sentence;for(const m of [...matches].reverse())masked=masked.slice(0,m.index)+'____'+masked.slice(m.index+m[0].length);
   // Character first names must not survive as an accidental answer giveaway.
   if(entity.forms.some(f=>new RegExp(`(?<![\\p{L}])${escape(f)}(?![\\p{L}])`,'u').test(masked)))continue;
   out.push({entity,sentence,masked,index,source,main:main.includes(entity.name),key:normalize(masked),position:matches[0].index});
  }
 }
 return out;
}
